name: DevOps Demo CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "No real tests yet, pipeline works!"

      - name: Simulate Deployment
        run: |
          echo "Deployment started..."
          mkdir -p deploy
          cp app.py deploy/
          echo "Deployment finished!"

      - name: Run Flask App (Demo)
        run: |
          echo "Starting Flask app for demo..."
          nohup python app.py &
          sleep 5
          echo "Flask app should be running (demo only)"
